"""empty message

Revision ID: 66055870f08e
Revises: 
Create Date: 2018-07-19 21:43:53.885933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66055870f08e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RequestList',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_url', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=10), nullable=False),
    sa.Column('request_header', sa.String(length=1000), nullable=False),
    sa.Column('datatype', sa.String(length=50), nullable=True),
    sa.Column('request_data', sa.String(length=1000), nullable=True),
    sa.Column('request_status', sa.String(length=10), nullable=False),
    sa.Column('tasktime', sa.String(length=215), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TaskList',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Request_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('TaskList')
    op.drop_table('RequestList')
    # ### end Alembic commands ###
